//
// Created by Tubetrue01 on 2022/8/10.
//
#include <string.h>
#include "streamingmedia.h"

#define NETFLIX_NUM 34
#define DISNEY_NUM 164

int is_media(const char *hostname)
{
    char *netflix[NETFLIX_NUM] = {
            "api.fast.com"
            ,"netflix.com.edgesuite.net"
            ,"fast.com"
            ,"flxvpn.net"
            ,"netflix.ca"
            ,"netflix.com"
            ,"netflix.com.au"
            ,"netflix.com.edgesuite.net"
            ,"netflix.net"
            ,"netflixdnstest0.com"
            ,"netflixdnstest1.com"
            ,"netflixdnstest10.com"
            ,"netflixdnstest2.com"
            ,"netflixdnstest3.com"
            ,"netflixdnstest4.com"
            ,"netflixdnstest5.com"
            ,"netflixdnstest6.com"
            ,"netflixdnstest7.com"
            ,"netflixdnstest8.com"
            ,"netflixdnstest9.com"
            ,"netflixinvestor.com"
            ,"netflixstudios.com"
            ,"netflixtechblog.com"
            ,"nflxext.com"
            ,"nflximg.com"
            ,"nflximg.net"
            ,"nflxsearch.net"
            ,"nflxso.net"
            ,"nflxvideo.net"
            ,"us-west-2.amazonaws.com"
            ,"apiproxy-device-prod-nlb-"
            ,"dualstack.apiproxy-"
            ,"dualstack.ichnaea-web-"
            ,"netflixdnstest"
    };

    char *disney[DISNEY_NUM] = {
            "20thcenturystudios.com.au"
            ,"20thcenturystudios.com.br"
            ,"20thcenturystudios.jp"
            ,"abc-studios.com"
            ,"abc.com"
            ,"abcnews.com"
            ,"abcnews.edgesuite.net"
            ,"adobedtm.com"
            ,"adventuresbydisney.com"
            ,"babble.com"
            ,"babyzone.com"
            ,"bam.nr-data.net"
            ,"bamgrid.com"
            ,"beautyandthebeastmusical.co.uk"
            ,"braze.com"
            ,"cdn.optimizely.com"
            ,"conviva.com"
            ,"d9.flashtalking.com"
            ,"dilcdn.com"
            ,"disney-asia.com"
            ,"disney-discount.com"
            ,"disney-plus.net"
            ,"disney-portal.my.onetrust.com"
            ,"disney-studio.com"
            ,"disney-studio.net"
            ,"disney.asia"
            ,"disney.be"
            ,"disney.bg"
            ,"disney.ca"
            ,"disney.ch"
            ,"disney.co.il"
            ,"disney.co.jp"
            ,"disney.co.kr"
            ,"disney.co.th"
            ,"disney.co.uk"
            ,"disney.co.za"
            ,"disney.com"
            ,"disney.com.au"
            ,"disney.com.br"
            ,"disney.com.hk"
            ,"disney.com.tw"
            ,"disney.cz"
            ,"disney.de"
            ,"disney.demdex.net"
            ,"disney.dk"
            ,"disney.es"
            ,"disney.fi"
            ,"disney.fr"
            ,"disney.gr"
            ,"disney.hu"
            ,"disney.id"
            ,"disney.in"
            ,"disney.io"
            ,"disney.it"
            ,"disney.my"
            ,"disney.my.sentry.io"
            ,"disney.nl"
            ,"disney.no"
            ,"disney.ph"
            ,"disney.pl"
            ,"disney.pt"
            ,"disney.ro"
            ,"disney.ru"
            ,"disney.se"
            ,"disney.sg"
            ,"disneyadsales.com"
            ,"disneyarena.com"
            ,"disneyaulani.com"
            ,"disneybaby.com"
            ,"disneycareers.com"
            ,"disneychannelonstage.com"
            ,"disneychannelroadtrip.com"
            ,"disneycruisebrasil.com"
            ,"disneyenconcert.com"
            ,"disneyiejobs.com"
            ,"disneyinflight.com"
            ,"disneyinternational.com"
            ,"disneyinternationalhd.com"
            ,"disneyjunior.com"
            ,"disneyjuniortreataday.com"
            ,"disneylandparis.com"
            ,"disneylatino.com"
            ,"disneymagicmoments.co.il"
            ,"disneymagicmoments.co.uk"
            ,"disneymagicmoments.co.za"
            ,"disneymagicmoments.de"
            ,"disneymagicmoments.es"
            ,"disneymagicmoments.fr"
            ,"disneymagicmoments.gen.tr"
            ,"disneymagicmoments.gr"
            ,"disneymagicmoments.it"
            ,"disneymagicmoments.pl"
            ,"disneymagicmomentsme.com"
            ,"disneyme.com"
            ,"disneymeetingsandevents.com"
            ,"disneymovieinsiders.com"
            ,"disneymusicpromotion.com"
            ,"disneynewseries.com"
            ,"disneynow.com"
            ,"disneypeoplesurveys.com"
            ,"disneyplus.bn5x.net"
            ,"disneyplus.com"
            ,"disneyplus.com.ssl.sc.omtrdc.net"
            ,"disneyprivacycenter.com"
            ,"disneyredirects.com"
            ,"disneysrivieraresort.com"
            ,"disneystore.com"
            ,"disneystreaming.com"
            ,"disneysubscription.com"
            ,"disneytermsofuse.com"
            ,"disneytickets.co.uk"
            ,"disneyturkiye.com.tr"
            ,"disneytvajobs.com"
            ,"disneyworld-go.com"
            ,"dlp-media.com"
            ,"dmed.technology"
            ,"dssott.com"
            ,"dtci.co"
            ,"dtci.technology"
            ,"edgedatg.com"
            ,"espn.co.uk"
            ,"espn.com"
            ,"espn.hb.omtrdc.net"
            ,"espn.net"
            ,"espncdn.com"
            ,"espndotcom.tt.omtrdc.net"
            ,"espnqa.com"
            ,"execute-api.us-east-1.amazonaws.com"
            ,"go-disneyworldgo.com"
            ,"go.com"
            ,"js-agent.newrelic.com"
            ,"marvel.com"
            ,"marvel10thanniversary.com"
            ,"marveldimensionofheroes.com"
            ,"marvelparty.ne"
            ,"marvelpinball.co"
            ,"marvelsdoubleagent.co"
            ,"marvelspotlightplays.co"
            ,"marvelsuperheroseptember.com"
            ,"marvelsuperwar.com"
            ,"mickey.tv"
            ,"moviesanywhere.com"
            ,"natgeomaps.com"
            ,"nationalgeographic.com"
            ,"nationalgeographicpartners.com"
            ,"ngeo.com"
            ,"nomadlandmovie.ch"
            ,"playmation.com"
            ,"shopdisney.com"
            ,"shops-disney.com"
            ,"sorcerersarena.com"
            ,"spaindisney.com"
            ,"star-brasil.com"
            ,"star-latam.com"
            ,"starwars.com "
            ,"starwarsgalacticstarcruiser.com"
            ,"starwarskids.com"
            ,"streamingdisney.net"
            ,"themarvelexperiencetour.com"
            ,"thestationbymaker.com"
            ,"thewaltdisneycompany.com"
            ,"thisispolaris.com"
            ,"watchdisneyfe.com"
            ,"watchespn.com"
    };
    char *sub_str;
    for (int i = 0; i < NETFLIX_NUM; i++)
    {
        sub_str = strcasestr(hostname, netflix[i]);
        if (sub_str)
        {
            return 1;
        }
    }
    for (int i = 0; i < DISNEY_NUM; i++){
        sub_str = strcasestr(hostname, disney[i]);
        if (sub_str)
        {
            return 1;
        }
    }
    return 0;
}


